package main

func handleErr(message string) {

}
